# Generated by Django 3.2.4 on 2021-06-21 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('main_teacher', models.IntegerField()),
                ('sub_teacher', models.IntegerField()),
                ('body', models.TextField()),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
                ('extrafile', models.FileField(null=True, upload_to='extrafiles/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
