# Generated by Django 3.2.4 on 2021-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edupost',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
