# Generated by Django 3.2.4 on 2021-06-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_edupost_count'),
        ('education', '0002_edupost_work_hour'),
    ]

    operations = [
    ]
