# Generated by Django 3.2.4 on 2021-06-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_merge_0002_edupost_count_0002_edupost_work_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='edupost',
            name='image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='edupost',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
