# Generated by Django 3.2.4 on 2021-06-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20210627_0057'),
        ('education', '0004_edupost_work_date'),
    ]

    operations = [
    ]
