# Generated by Django 3.2.4 on 2021-06-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='HS',
        ),
        migrations.AlterField(
            model_name='apply',
            name='phone_num',
            field=models.CharField(max_length=11),
        ),
    ]
