# Generated by Django 3.2.4 on 2021-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20210625_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='winner',
            field=models.CharField(default='', max_length=10),
        ),
    ]
