# Generated by Django 3.2.4 on 2021-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_apply_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='total_work',
            field=models.IntegerField(default=0),
        ),
    ]
