# Generated by Django 3.2.4 on 2021-06-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_apply_total_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
